name: Build OpenWrt Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v3
        with:
          repository: openwrt/openwrt
          ref: openwrt-23.05

      - name: Setup OpenWrt Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git unzip wget

      - name: Clone luci-app-nekoclash Repository
        run: |
          git clone https://github.com/zesssttt/luci-app-nekoclash.git
          
      - name: Copy luci-app-nekoclash to OpenWrt Packages
        run: |
          cp -r luci-app-nekoclash/package/* openwrt/package/

      - name: Configure OpenWrt Build
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build OpenWrt
        run: |
          cd openwrt
          make menuconfig
          make -j$(nproc) V=s

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-build
          path: openwrt/bin/
