name: Build IPK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache libncurses5-dev zlib1g-dev gawk flex gettext wget unzip python3-distutils
          wget https://downloads.openwrt.org/releases/22.03.3/targets/x86/64/openwrt-sdk-x86_64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          tar xf openwrt-sdk-x86_64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          export SDK_DIR=$(pwd)/openwrt-sdk-x86_64_gcc-8.4.0_musl.Linux-x86_64
          cd $SDK_DIR

      - name: Install Dependencies
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Package
        run: |
          cd $SDK_DIR/package
          git clone https://github.com/zesssttt/luci-app-nekoclash.git
          cd luci-app-nekoclash
          ./scripts/feeds install luci-app-nekoclash
          cd $SDK_DIR
          make menuconfig
          make package/luci-app-nekoclash/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-nekoclash-ipk
          path: $SDK_DIR/bin/packages/x86_64/base/luci-app-nekoclash_*.ipk
