name: Build OpenWRT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3

    - name: Clone OpenWRT Source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v22.03.0

    - name: Add Luci App NekoClash
      run: |
        cd openwrt/package
        git clone https://github.com/zesssttt/luci-app-nekoclash.git
        cd ..

    - name: Update Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure Build
      run: |
        cp .config.seed .config
        make defconfig

    - name: Build OpenWRT
      run: |
        make -j$(nproc) V=s

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: openwrt/bin/targets/
