name: Build OpenWrt Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup OpenWrt Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses5-dev zlib1g-dev gawk flex gettext wget unzip

      - name: Clone OpenWrt Source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add Custom Feed for luci-app-nekoclash
        run: |
          echo "src-git nekoclash https://github.com/zesssttt/luci-app-nekoclash.git" >> openwrt/feeds.conf.default
          
      - name: Build luci-app-nekoclash Package
        run: |
          cd openwrt
          make menuconfig # Optional: For interactive configuration, usually not required in CI
          make package/luci-app-nekoclash/compile V=s

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-packages
          path: openwrt/bin/packages/*/*/*.ipk
