name: Build OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache zlib1g-dev libncurses5-dev gawk flex quilt libssl-dev xsltproc wget unzip python3
        mkdir -p ~/openwrt
        cd ~/openwrt
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05

    - name: Add custom package feeds
      run: |
        cd ~/openwrt
        echo "src-git nekoclash https://github.com/zesssttt/luci-app-nekoclash.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build OpenWrt
      run: |
        cd ~/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make -j$(nproc) download
        make -j$(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-build
        path: |
          ~/openwrt/bin/
          ~/openwrt/bin/targets/
          ~/openwrt/bin/packages/
