name: Build IPK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git subversion

      - name: Install OpenWrt build dependencies
        run: |
          sudo apt-get install -y zlib1g-dev libncurses5-dev gawk flex quilt curl libssl-dev xsltproc wget unzip

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add custom feed
        run: |
          cd openwrt
          echo 'src-git luci https://github.com/openwrt/luci.git' >> feeds.conf.default
          echo 'src-git nekoclash https://github.com/zesssttt/luci-app-nekoclash.git' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build package
        run: |
          cd openwrt
          make menuconfig # Optional, configure build settings manually
          make package/luci-app-nekoclash/compile V=s

      - name: Archive IPK
        uses: actions/upload-artifact@v3
        with:
          name: ipk-package
          path: |
            openwrt/bin/packages/*/*/luci-app-nekoclash_*.ipk
