name: Build IPK for luci-app-nekoclash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git subversion
          sudo apt-get install -y zlib1g-dev libncurses5-dev gawk flex quilt curl libssl-dev xsltproc wget unzip

      - name: Clone OpenWrt source
        run: |
          git clone --branch openwrt-23.05 https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add custom feeds
        run: |
          cd openwrt
          echo 'src-git nekoclash https://github.com/zesssttt/luci-app-nekoclash.git' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          cd openwrt
          # Optionally, you can use a default configuration file if available
          # cp /path/to/your/.config .config
          make menuconfig # This step is optional and allows manual configuration

      - name: Build luci-app-nekoclash
        run: |
          cd openwrt
          make package/luci-app-nekoclash/compile V=s

      - name: Archive IPK files
        uses: actions/upload-artifact@v3
        with:
          name: ipk-package
          path: |
            openwrt/bin/packages/*/*/luci-app-nekoclash_*.ipk
