name: Build IPK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenWrt build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            wget \
            unzip \
            libncurses5-dev \
            zlib1g-dev \
            gawk \
            flex \
            quilt \
            subversion \
            libssl-dev \
            xsltproc \
            perl \
            gettext \
            python3

      - name: Install OpenWrt build system
        run: |
          mkdir -p ~/openwrt
          cd ~/openwrt
          git clone https://github.com/openwrt/openwrt.git .
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy package files
        run: |
          mkdir -p ~/openwrt/package
          cp -r ./* ~/openwrt/package/

      - name: Build package
        run: |
          cd ~/openwrt
          make menuconfig
          make package/luci-app-nekoclash-mod/compile V=s

      - name: Archive IPK files
        uses: actions/upload-artifact@v3
        with:
          name: ipk-files
          path: |
            ~/openwrt/bin/packages/*/*.ipk
