name: Building IPK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'
        type: string
      changelog:
        description: 'Changelog'
        required: true
        default: ''
        type: string
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build IPK5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Preparing IPK
        run: |
              echo ""
              git clone https://github.com/Houjie80/luci-app-nekoclash
              mkdir feeds artifacts
              cp -rf ./luci-app-nekoclash ./feeds
        
      - name: Building IPK
        uses: Houjie80/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-nekoclash
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-nekoclash-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-nekoclash*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-nekoclash-21.02.7_x86_64/* ./release/luci-app-nekoclash_${{ inputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-nekoclash-23.05.0_x86_64/* ./release/luci-app-nekoclash_${{ inputs.version }}_all_23_05.ipk
  
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: ${{ inputs.version }}
          file_glob: true
          body: |
            # LUCI APP NEKOCLASH ${{ inputs.version }}
            droidnet
            ### Information
            - Changelog : 
              - ${{ inputs.changelog }}
